name: studybeats
description: "Interactive productivity suite"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: '3.29.0'


dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.40
  audio_session: ^0.1.18
  rxdart: ^0.28.0
  quiver: ^3.2.1
  marquee: ^2.2.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  flutter_audio_waveforms: ^1.2.1+8
  card_swiper: ^3.0.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_ui_auth: ^1.15.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  firebase_storage: ^12.1.1
  uuid: ^4.4.2
  intl: ^0.19.0
  image_picker_web: ^4.0.0

  universal_html: ^2.2.4
  flutter_markdown: ^0.7.3
  lottie: ^3.1.2
  dio: ^5.5.0+1
  universal_io: ^2.2.2
  logger: ^2.4.0
  flutter_stripe: ^11.0.0
  shimmer: ^3.0.0




  

  http: ^1.4.0
  marquee_text: ^2.5.0+1
  text_marquee: ^0.0.2
  google_fonts: ^6.2.1
  get: ^4.6.6
  share_plus: ^10.0.0
  go_router: ^14.2.7
  url_strategy: ^0.3.0
  skeletonizer: ^1.4.2
  flutter_secure_storage: ^9.2.2
  sentry_flutter: ^8.9.0
  firebase_analytics: ^11.3.3
  animated_reorderable_list: ^1.1.3
  flutter_datetime_picker_plus: ^2.2.0
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.4.4
  flutter_quill: ^11.0.0
  openai_dart: ^0.4.5
  tiktoken: ^1.0.3
  cloud_functions: ^5.3.4
  package_info_plus: ^8.3.0
  flutter_localization: any
  fl_chart: ^0.71.0
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.5
  test: ^1.25.15
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  web: ^1.1.1
  flutter_svg: ^2.1.0
  spotify_sdk: ^3.0.2
  flutter_dotenv: ^5.2.1
  js: ^0.6.7



  equatable: any
  one_clock: ^2.0.1
  reorderables: ^0.6.0
  weather: ^3.2.1
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  geolocator_web: ^4.1.3
  fl_location: ^5.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependency_overrides:
  fading_edge_scrollview: ^4.1.1

flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/brand/
    - assets/animations/
    - assets/flat/
