name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.27.0' # Specify Flutter version
          
          channel: beta
          cache: true
    
      - name: Disable web caching
        run: bash ./build-web.sh
      
      - name: Decode base64 secrets
        run: |
          echo "${{ secrets.SECRETS_FILE_CONTENT }}" | base64 -d > lib/secrets.dart
      
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: Set CORS Configuration
        run: gsutil cors set ./cors.json ${{ secrets.BUCKET_NAME }}
        
      - name: Build Flutter Web App
        run: flutter build web --no-tree-shake-icons --web-renderer html --release # Uses the specified Flutter version
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLOURISH_WEB_FA343 }}
          channelId: live
          projectId: flourish-web-fa343
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks